Title
========================================================

Once upon a time, the great city of Normalville thrived ontop of Normal Mountain. This mountain had special properties and all of the Normans, the name given to these people, were happy and worked together in peace. 

```{r}
x = rnorm(1000)
library(ggplot2)
qplot(x, geom="Histogram")
```


One day Mr. Chi was balancing the daily variance of the city and noticed a HUGE problem. The variance was negative. 

All at once, the world seemed upside down, the groud shook violently and the citizens were tossed off out to Normalville, off Normal Mountain, and into the cold valley below. They watched, paralyzed in fear, as their once great mountain dissapeared into rubble. 






Down in Cauchy Valley, the land of no mean or variance, the one great citizens of Normalville clung to survival through freezing winters and brutally hot summers. Without the normal curve, citzens no longer knew how to estimate the temperature and made very poor clothing choices. 

One day, when Mr. Chi was walking around Cauchy Valley, he found a little boy crying. "Why are you crying?" asked Mr. Chi. The boy, in utter despair, responded, "because I cannot find out the probability that I will score between a 75 and a 95 on my upcoming exam!" These were serious times. 

The Abnormal people watched from afar as the Normans struggled to become accustomed to Cauchy Valley. They hated the Normans and had been plotting their revenge since 30 years  earlier when King Normal IV sentenced them to exile because they couldn't generate enough moments. Now they had the upper-hand and they were prepared crush the people of Normalville once and for all!


The fight began and the Normans were left utterly defenseless without their precious mean and variance assumption. They couldn't predict the Abnormals' movements, much less their heights, weights, and foot lengths. 




